### ISSUE TITLE
Cross referencing / goto definition

### ISSUE THREAD

**Issue by florianschanda** [bmw-software-engineering/trlc-vscode-extension#10]
Two use-cases (but internally this is probably the same code path):
```trlc
Requirement Potato {
   description = "potato"
   relates_to = [Kitten, foo.Wibble]
}
```

Ordered from most important to least important
* clicking on `Kitten` or `Wibble` -> goto definition should take you to the trlc file where they are defined
* clicking on `Requirement` -> goto definition should take you to the rsl file where `Requirement` is defined
* (bonus) clicking on `description` or `relates_to` -> goto definition should take you to the rsl file the those components are defined
* (bonus) clicking on `foo` should maybe take you to the package rsl, if it exists?

**Comment by markusrosskopf** [comment]
Done with 661bfdfece4ca9a01496cc269201ad3487505012
