### ISSUE TITLE
Context menu features

### ISSUE THREAD

**Issue by florianschanda** [bmw-software-engineering/trlc-vscode-extension#2]
- [x] Find all references
- [x] Go to definition
- [x] Go to references
- [x] Peek definition
- [x] Peek references
- [x] Rename symbol (to conveniently rename every occurrence)

Available for type, record reference and package.

**Comment by markusrosskopf** [comment]
'Rename Symbol' with 661bfdfece4ca9a01496cc269201ad3487505012
'Find Reference' with 661bfdfece4ca9a01496cc269201ad3487505012
'Go To Definition' with 661bfdfece4ca9a01496cc269201ad3487505012
