### ISSUE TITLE
Autocomplete non-optional components

### ISSUE THREAD

**Issue by florianschanda** [bmw-software-engineering/trlc-vscode-extension#4]
Available for:
1.  Record
2. Tupel

**Feature:**
- feature is activated as soon as the record identifier is finished (e.g. space or `{` pressed)
- feature inserts all mandatory attributes followed by `=` sign
- no values are proposed for the attributes
- indention must match (e.g. auto-completion inside sections must indent the text further)

**Example:**
The user types
```
Requirement Some_Identifier {
```
and it will be turned into
```
Requirement Some_Identifier {
  description =
  other_value = 
  whaterver =
}
```

**Comment by markusrosskopf** [comment]
Done with 661bfdfece4ca9a01496cc269201ad3487505012
